server:
  HttpUser: root
  HttpPassword: root@123
  ServerModifyLineNumber: 43
#  ConfigFilePath: /Users/ld/my-file/workspace/go_own/proxy-autoport/resource/config.json
  ConfigFilePath: /usr/local/x-ui/bin/config.json
#  ChangePortShellPath: /Users/ld/my-file/workspace/go_own/proxy-autoport/resource/change-port.sh
  ChangePortShellPath: /root/sh/change-port.sh
  DefaultPort: 42001
  HttpPort: 37001
  GetPortShellPath: /root/sh/get-port.sh
client:
  ClashServer: http://localhost:9090
  ClashSecret: secret@123
  ConfitFilePath: /Users/ld/.config/clash/config.yaml
  ServerIP: serverip
  TestUrl: http://www.gstatic.com/generate_204&timeout=10000

